# Generated by Django 3.2 on 2021-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
                ('population', models.PositiveIntegerField()),
                ('total_cases', models.PositiveIntegerField()),
                ('new_cases', models.PositiveIntegerField()),
                ('active_cases', models.PositiveIntegerField()),
                ('cases_1m_pop', models.PositiveIntegerField()),
                ('total_deaths', models.PositiveIntegerField()),
                ('new_deaths', models.PositiveIntegerField()),
                ('deaths_1m_pop', models.PositiveIntegerField()),
                ('total_recovered', models.PositiveIntegerField()),
                ('new_recovered', models.PositiveIntegerField()),
                ('infection_risk', models.FloatField()),
                ('case_fatality_rate', models.FloatField()),
                ('recovery_proportion', models.FloatField()),
                ('total_vaccinated', models.PositiveIntegerField()),
                ('vaccinated_proportion', models.FloatField()),
                ('vaccinated_1m_pop', models.PositiveIntegerField()),
            ],
        ),
    ]
