# Generated by Django 3.2 on 2021-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('specific_country', models.CharField(blank=True, default='', max_length=50)),
                ('all_countries', models.BooleanField()),
                ('interval', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
