# Generated by Django 3.2 on 2021-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20210506_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.URLField(null=True),
        ),
    ]
