# Generated by Django 3.2 on 2021-05-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20210506_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
