# Generated by Django 3.2 on 2021-05-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_country_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='total_vaccinated',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='vaccinated_1m_pop',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='vaccinated_proportion',
            field=models.FloatField(null=True),
        ),
    ]
