# Generated by Django 3.2 on 2021-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_country_flag_url_big'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_pt',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
