# Generated by Django 3.2 on 2021-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_country_flag_url_shiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_url_big_shiny',
            field=models.URLField(null=True),
        ),
    ]
