# Generated by Django 3.2 on 2021-05-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_country_flag_url_big_shiny'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastModified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
