# Generated by Django 3.2 on 2021-05-20 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_auto_20210517_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmodified',
            name='last_modified_data',
            field=models.CharField(default=datetime.date(2021, 5, 20), max_length=20),
        ),
    ]
