# Generated by Django 3.2 on 2021-06-01 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_alter_lastmodified_last_modified_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmodified',
            name='last_modified_data',
            field=models.CharField(default=datetime.date(2021, 6, 1), max_length=20),
        ),
    ]
